Update index.js
Changed jasmine-cucumber path to root because cause a issue :
```
Error: Cannot find module '../node_modules/jasmine-cucumber/src/jasmine-cucumber.js'
```